# Important Notes:
# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.

# Project
version=1.0.0
group=com.turbocrackers.bettervillagespawnpoint

# Common
minecraft_version=1.20.6
mod_name=BetterVillageSpawnPoint
mod_author=TurboCrackers
mod_id=bettervillagespawnpoint
license=CC0-1.0
credits=
description=A mod that automatically sets the spawn point to a reasonable spot in the nearest village from a configurable list of village IDs\n\n(example: minecraft:village_plains) and/or tags (example: #minecraft:villages).\n\nIt tries really hard to put you on the ground if it can, as opposed to other mods that will spawn you in a tree or on an island above a village.
minecraft_version_range=[1.20.6, 1.21)
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.20.6-20240627.102356
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.20.6
parchment_version=2024.06.16

# Fabric
# https://fabricmc.net/develop/
fabric_version=0.100.8+1.20.6
fabric_loader_version=0.16.14
cloth_config_api_version=14.0.139

# Forge
# https://files.minecraftforge.net/net/minecraftforge/forge/
forge_version=50.2.0
forge_loader_version_range=[50,)

# NeoForge
# https://neoforged.net/
neoforge_version=20.6.138
neoforge_loader_version_range=[3,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Java
java_version=21
java_version_name=JAVA_21