# Important Notes:
# fabric.mod.json's modid field cannot be expanded, you must change it manually.
# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.

# Project
version=1.0.4
group=com.turbocrackers.bettervillagespawnpoint
java_version=25

# Common
minecraft_version=26.1.1
mod_name=BetterVillageSpawnPoint
mod_author=TurboCrackers
mod_id=bettervillagespawnpoint
license=CC0-1.0
credits=
description=A mod that automatically sets the spawn point to a reasonable spot in the nearest village from a configurable list of village IDs\n\n(example: minecraft:village_plains) and/or tags (example: #minecraft:villages).\n\nIt tries really hard to put you on the ground if it can, as opposed to other mods that will spawn you in a tree or on an island above a village.
minecraft_version_range=[26.1.1, 27)
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
# https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.1.1-1
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=
parchment_version=

# Fabric
# https://fabricmc.net/develop/
fabric_version=0.145.4+26.1.1
fabric_loader_version=0.19.5

# Forge
# https://files.minecraftforge.net/net/minecraftforge/forge/
forge_version=63.0.2
forge_loader_version_range=[63,)

# NeoForge
# https://neoforged.net/
neoforge_version=26.1.1.15-beta
neoforge_loader_version_range=[4,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Loom task that produces the distributable Fabric jar: remapJar while Minecraft was obfuscated, plain jar from 26.1 on.
fabric_jar_task=jar
